import type { NextPage } from "next";
import Head from "next/head";
import styles from "./[index].module.scss";
import { Container, Link, Spacer, Text } from "@nextui-org/react";
import NextLink from "next/link";
import EchTheme from "@/components/common/themes/index";
import { EchCardTvShow } from "@/components/tvshows/cardList";
import { getTvShowDetails } from "@/pages/api/tvshows/[id]";

// @ts-ignore
const TvShowDetails: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: TvShow Details</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spacer />
      <Container
        as="main"
        display={"flex"}
        alignContent={"space-between"}
        justify={"space-between"}
      >
        <NextLink href={`/`}>
          <Link color="secondary">
            <Text h2>Estrenos Cine Hoy</Text>
          </Link>
        </NextLink>
        <EchTheme />
      </Container>
      <Spacer />
      <Container as="section">
        <Text h1>{data.name}</Text>
        <Text h5>{data.tagline && `"${data.tagline}"`}</Text>
        <Spacer />
      </Container>
      <Container
        as="section"
        display={"flex"}
        alignContent={"space-between"}
        justify={"space-evenly"}
        responsive={true}
      >
        <section className={styles["section-overview"]}>
          <EchCardTvShow {...data}></EchCardTvShow>
        </section>
        <Spacer />
        <section className={styles["section-overview"]}>
          <Text h5>{`"Overview"`}</Text>
          <Text h6>{data.overview}</Text>
        </section>
        <Spacer />
        {/*<section className={styles["section-credits"]}>*/}
        {/*  <EchCardCredits cast={data.credits.cast} />*/}
        {/*</section>*/}
      </Container>
      <Spacer />
    </div>
  );
};

// @ts-ignore
export const getServerSideProps = async ({ params, query }) => {
  // @ts-ignore
  // https://www.learnbestcoding.com/post/25/nextjs-how-to-use-getServerSideProps
  const tvShowDetails = await getTvShowDetails({
    id: query.index,
    language: query.language,
  });
  return {
    props: {
      data: tvShowDetails,
    },
  };
};

export default TvShowDetails;
