import type { NextPage } from "next";
import Head from "next/head";
import styles from "./[index].module.scss";
import { Container, Link, Spacer, Text } from "@nextui-org/react";
import NextLink from "next/link";
import { EchCardMovie } from "@/components/movies";
import { getMovieDetails } from "@/pages/api/movies/[id]";
import EchCardCredits from "@/components/credits/index";
import Theme from "@/components/themes/themes";

// @ts-ignore
const MovieDetails: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: Movie Details</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main">
        <Spacer />
        <Theme />
        <NextLink href={`/`}>
          <Link color="secondary">
            <Text h1>Estrenos Cine</Text>
          </Link>
        </NextLink>
        <Spacer />
      </Container>
      <Container as="section">
        <Text h4>{data.title}</Text>
        <Text h5>{`"${data.tagline}"`}</Text>
        <Spacer />
      </Container>
      <Container
        as="section"
        display={"flex"}
        alignContent={"space-between"}
        justify={"space-evenly"}
        responsive={true}
      >
        <section className={styles["section-overview"]}>
          <EchCardMovie {...data}></EchCardMovie>
        </section>
        <Spacer />
        <section className={styles["section-overview"]}>
          <Text h5>{`"Overview"`}</Text>
          <Text h6>{data.overview}</Text>
        </section>
        <Spacer />
        <section className={styles["section-credits"]}>
          <EchCardCredits cast={data.credits.cast} />
        </section>
      </Container>
      <Spacer />
    </div>
  );
};

// @ts-ignore
export const getServerSideProps = async ({ params, query }) => {
  // @ts-ignore
  // https://www.learnbestcoding.com/post/25/nextjs-how-to-use-getServerSideProps
  const movieDetails = await getMovieDetails({
    id: query.index,
    language: query.language,
  });
  return {
    props: {
      data: movieDetails,
    },
  };
};

export default MovieDetails;
