import type { NextPage, PreviewData } from "next";
import Head from "next/head";
import styles from "./[index].module.css";
import { Container, Spacer, Text } from "@nextui-org/react";
import Theme from "@/components/themes/themes";
import { EchCardMovie } from "@/components/movies";
import { getMovieDetails } from "@/pages/api/movies/[id]";
import EchGrid from "@/components/grid";

// @ts-ignore
const MovieDetails: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: Movie Details</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" display="inline">
        <Spacer />
        <Theme />
        <Text h1 className={styles.title}>
          Estrenos Cine Hoy
        </Text>
        <Spacer />
      </Container>
      <EchGrid>
        <EchCardMovie {...data}></EchCardMovie>
      </EchGrid>
    </div>
  );
};

// @ts-ignore
export const getServerSideProps = async ({ params, query }) => {
  // @ts-ignore
  // https://www.learnbestcoding.com/post/25/nextjs-how-to-use-getServerSideProps
  const movieDetails = await getMovieDetails({
    id: query.index,
    language: query.language,
  });
  return {
    props: {
      data: movieDetails,
    },
  };
};

export default MovieDetails;
