import type { NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.scss";
import { Container, Spacer, Text } from "@nextui-org/react";
import EchCardMovies from "@/components/movies/cardList/index";
import EchGrid from "@/components/common/grid";
import { getTrending } from "@/pages/api/trending/[...index]";
import EchHeader from "@/components/common/header";

// @ts-ignore
const EchHome: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: Trending Movies</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spacer />
      <EchHeader />
      <Spacer />
      <Container as="section">
        <Text h1>Trending Movies</Text>
        <Spacer />
      </Container>
      <Container as="section">
        <EchGrid>
          <EchCardMovies data={data}></EchCardMovies>
        </EchGrid>
      </Container>
    </div>
  );
};

// @ts-ignore
export const getServerSideProps: GetServerSideProps = async ({
  // @ts-ignore
  params,
  // @ts-ignore
  query,
}) => {
  const trendingMovies = await getTrending({
    resource: "movies",
    period: "week",
    language: "es-ES",
  });
  return {
    props: {
      data: trendingMovies,
    },
  };
};

export default EchHome;
