import type { NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.scss";
import { Container, Spacer, Text } from "@nextui-org/react";
import Theme from "@/components/themes/themes";
import EchCardMovies from "@/components/movies";
import { getTrending } from "@/pages/api/trending/[...index]";
import EchGrid from "@/components/grid";

// @ts-ignore
const EchHome: NextPage = ({ data }) => {
  debugger;
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: Trending Movies</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" display="inline">
        <Spacer />
        <Theme />
        <Text h1 className={styles.title}>
          Estrenos Cine Hoy
        </Text>
        <Spacer />
      </Container>
      <EchGrid>
        <EchCardMovies data={data}></EchCardMovies>
      </EchGrid>
    </div>
  );
};

// @ts-ignore
export const getServerSideProps: GetServerSideProps<Context<string>> = async (
  // @ts-ignore
  context
) => {
  const trendingMovies = await getTrending({
    resource: "movies",
    period: "week",
    language: "es-ES",
  });
  return {
    props: {
      data: trendingMovies,
    },
  };
};

export default EchHome;
