import type { NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.scss";
import { Container, Link, Spacer, Text } from "@nextui-org/react";
import EchCardMovies from "@/components/movies";
import { getTrending } from "@/pages/api/trending/[...index]";
import EchGrid from "@/components/grid";
import NextLink from "next/link";
import EchTheme from "@/components/themes/index";

// @ts-ignore
const EchHome: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estrenos Cine Hoy: Trending Movies</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spacer />
      <Container
        as="main"
        display={"flex"}
        alignContent={"space-between"}
        justify={"space-between"}
      >
        <NextLink href={`/`}>
          <Link color="secondary">
            <Text h2>Estrenos Cine Hoy</Text>
          </Link>
        </NextLink>
        <EchTheme />
      </Container>
      <Spacer />
      <Container as="section">
        <Text h1>Trending Movies</Text>
        <Spacer />
      </Container>
      <Container as="section">
        <EchGrid>
          <EchCardMovies data={data}></EchCardMovies>
        </EchGrid>
      </Container>
    </div>
  );
};

// @ts-ignore
export const getServerSideProps: GetServerSideProps<Context<string>> = async (
  // @ts-ignore
  context
) => {
  const trendingMovies = await getTrending({
    resource: "movies",
    period: "week",
    language: "es-ES",
  });
  return {
    props: {
      data: trendingMovies,
    },
  };
};

export default EchHome;
